### ISSUE TITLE
800px & Different Save Data Location

### ISSUE THREAD

**Issue by The0zymandias** [BlyZeYT/T-Rex-Game-3DS#1]
Hello, 

I really like this project and plan on downloading it when I am able. However, I have two suggestions:
1. Have the game run in 800x240 instead of 400x240 (this can be done by calling "gfxSetWide(true)" after "gfxInitDefault()" and simply increases the resolution the game runs at. Old 2DS models don't support this, so you might need to add a check about the console model to prevent crashing (I have no idea if calling the function will crash an old 2ds or simply not do anything).
2. If the user chooses to download the .cia version, the folder in /3ds is still created and used. A lot of apps do this, leading to a situation where the Homebrew Menu shows a bunch of folders that the user has to scroll down through to see homebrew. For this reason, many projects like Red Viper and Streetpass write their save data and configs to the /config/[app-name] folder instead of /3ds/[app-name].

**Comment by BlyZeDev** [comment]
Hi,

Thank you 😄

1. Yeah I can do that. I wasn't 100% sure if this would maybe fuck up some calculations. But after some testing I think it's fine.
2. Good idea, i will change this in the new release. Thank you for pointing that out

New Release will come some time this week ^^
